### ISSUE TITLE
Ordering of Docs in sidebar

### ISSUE THREAD

**Issue by spenot09** [autonity/docs.autonity.org#115]
### Description

The high-level execution order to become a registered Validator is:
- Spin up a node
- Run an Oracle server
- Register as a Validator

I suggest to order the docs in this sequence as well in the sidebar, so Validators avoid jumping around the docs articles.

The current order of relevant Docs articles is:
- Running a Node
- Running a Validator
- Running an Oracle Server

Which I propose to be:
- Running a Node
- Running an Oracle Server
- Running a Validator

### Rationale

In order to make the Validator onboarding experience as seamless as possible and minimise the amount of time team intervention is needed to get them up and running, I believe such an improvement in the Docs could help facilitate that.
### Implementation
It is currently not clear to me what controls the ordering of the sidebar. @dweng0 do you perhaps have an idea on the implementation of this?

**Comment by aiman** [comment]
In Hugo it is the `weight` specified in the yaml metadata that controls the ordering of items.

**Comment by jay-cousins** [comment]
I've revised following discussion with @spenot09 the ordering:

**FROM:**

- Overview
- Accounts
- Staking
- Running a Node
- Borrowing by CDP in the ASM
- Running a Validator
- Running an Oracle Server
- Development
- Networks
- Concepts
- Reference
- Glossary
- Known Issues

**TO:**

- Overview
- Concepts
- Networks
- Accounts
- Running a Node
- Running an Oracle Server
- Running a Validator
- Staking
- Borrowing by CDP in the ASM
- Development
- Reference
- Glossary
- Known Issues
