### ISSUE TITLE
Blank entries in Piccadilly and Bakerloo genesis configuration tables

### ISSUE THREAD

**Issue by aiman** [autonity/docs.autonity.org#13]
The corresponding values for genesis configuration fields:

- config.autonity.operator
- config.autonity.treasury  
- config.autonity.validators  

are currently blank in the corresponding genesis configuration pages for Piccadilly and Bakerloo.

I believe the values should not be blank, but rather they are simply missing from the table. So the table is incomplete.

Moreover, this looks visually jarring.

I would suggest either removing the entries (with explanation?) or completing the data in the tables.

See:

- content/docs/networks/testnet-bakerloo/_index.md
- content/docs/networks/testnet-piccadilly/_index.md

**Comment by jay-cousins** [comment]
Edits made in PR #55
