### ISSUE TITLE
endpoint sends a key with Access Denied

### ISSUE THREAD

**Issue by inspector44** [autonity/docs.autonity.org#130]
**Describe the bug**

https://game.autonity.org/account-holders/ endpoint is returning a key with Access Denied. I guessed that this might not be a desired behavior. I suspected a security vulnerability

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to ['https://docs.autonity.org/delegators/bond-stakee/'](https://game.autonity.org/account-holders/)
4. See a key with "Access Denied" test

**Device information (please complete the following information):**

- Device: [e.g. Desktop, Smartphone, Tablet]
- Browser Version [e.g. 22]

**Comment by inspector44** [comment]
I've seen this happen for every url that doesn't exist. If it's considered a vulnerability, I can close this issue and follow the vulnerability reporting process. Please let me know if there is anything you expect from me.

**Comment by jay-cousins** [comment]
Hi @inspector44 thanks for reporting this.

The page game.autonity.org/account-holders doesn't exist, so to get an access denied trying to resolve a URI that doesn't exist is not a CV.

**Comment by jay-cousins** [comment]
The issue here I think is one of returning a [403 Forbidden](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) access denied rather than a [404 Not Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404) .

**Comment by jay-cousins** [comment]
Thank you for reporting this @inspector44 and it is being looked at. This isn't an issue for the docs.autonity.org repo so this issue will be closed here and doesn't count towards the PCGC Bug Bounty.
