### ISSUE TITLE
validator registr form

### ISSUE THREAD

**Issue by UnicorNn1** [autonity/docs.autonity.org#136]
When I checked the documents, I found 2 different registration forms. Later, when I wanted to apply as a validator, there were 2 different forms again. The place where I got the error is that I cannot send any of the forms.

**Comment by dweng0** [comment]
Hey @Unicorn1807,

Seems like there's a bit of a mix-up with the forms. For a quicker fix, could you hop onto our Discord? It's easier to sort things out there, and you'll get help from both our team and the community. Check us out here: [Autonity Discord Server](https://discord.com/invite/autonity). See you there!

**Comment by UnicorNn1** [comment]
Yes, you are right, there is some confusion. Thank you for the information and support
