### ISSUE TITLE
Validator re-activation: sentence to modify.

### ISSUE THREAD

**Issue by jfaiza** [autonity/docs.autonity.org#143]
Hello,

In the re-activation part of the validator documentation, I noticed a sentence to modify.
   
![doc reactivate funtion doc bug](https://github.com/autonity/docs.autonity.org/assets/79405564/08fc62bc-cc64-4c6c-b8a7-88ff0d2ee06a)

I propose to modify the term marked in yellow from "**pause**" to "**inactive state (paused or jailed)**"
  So the sentence becomes >> "The validator’s state is changed from **inactive state (paused or jailed)** to active."

Steps to reproduce the behaviour:
1. Go to https://docs.autonity.org/concepts/validator/#validator-re-activation

**Comment by jay-cousins** [comment]
Thank you for spotting this inconsistency and suggested improvement @jfaiza .

Two changes made to fix:

- edit page https://docs.autonity.org/concepts/validator/#validator-re-activation per your suggestion to "The validator's state is changed from its inactive state (`paused` or `jailed`) to `active`."
- edit page https://docs.autonity.org/validators/pause-vali/#re-activate-a-validator . Same issue, a reword in Step 1 of this section from:

>1. To resume a validator from a paused to an active state, use the `validator` command `activate`. Specify:

- To:

>1. To resume a validator from an inactive state (`paused` or `jailed`) to an `active` state, use the `validator` command `activate`. Specify:

**Comment by jay-cousins** [comment]
Edits made in PR #144
