### ISSUE TITLE
Validator documentation: Add possible values of the Validator State 

### ISSUE THREAD

**Issue by jfaiza** [autonity/docs.autonity.org#145]
Hello,

I suggest adding in the validator documentation the possible values of the Validator State. I didn't find this information in the documentation. I identified them by doing tests.

- 0: ACTIVE

- 1: PAUSE

- 2: JAIL

Steps to reproduce the behaviour:
1. Go to https://docs.autonity.org/concepts/validator/

**Comment by jay-cousins** [comment]
Hi, thank you for this. The enumerations are listed out in the interface page for https://docs.autonity.org/reference/api/aut/#getvalidator in the Validator response object section:

### Response

Returns a `Validator` object consisting of:

| Field | Datatype | Description |
| --| --| --|
| ...|
| `ValidatorState` | `state` | the state of the validator. `ValidatorState` is an enumerated type with enumerations: `active`, `paused`, `jailed` |

But that is incorrect as `0`,`1`, `2` is returned. So, it should be

| Field | Datatype | Description |
| --| --| --|
| ...|
| `ValidatorState` | `state` | the state of the validator. `ValidatorState` is an enumerated type with enumerations: `0`: active, `1`: paused, `2`: jailed |
