### ISSUE TITLE
Upgrade Doc site to Quarto

### ISSUE THREAD

**Issue by dweng0** [autonity/docs.autonity.org#148]
### Description
This issue is for tracking the upgrade to [Quarto](https://quarto.org/) and will be used to track the progress as well as highlight any outstanding tasks left to do.

### Functional updates
- [x] Run scripts to upgrade shortcodes.
- [x] Update the external links so that quarto automatically applies icons.
- [x] Update github workflows to allow for quarto deployments
- [x] Update github to clean up any unnecessary tracked files.
- [x] Setup Gh-pages Once merged into develop

### Gotchas

- It is recommended that users Clone a fresh version locally as some hugo files may linger causing `quarto render` to fail
- If a fresh clone cannot be done. remove the following files:
``` bash
 themes/
```

**Comment by dweng0** [comment]
Following the deployment process for Quarto, [here](https://quarto.org/docs/publishing/github-pages.html#github-action), I appear to not be able to publish the site to gh-pages. I believe this is a permissions issue as this is the process I used for the games site. Will investigate this further, FYSA @raj-shekhar1 @Klazomenai  @aiman

**Comment by aiman** [comment]
@dweng0 I recommend creating a separate sandbox repo in order to test and debug Github workflows and interactions with branches and publication.

**Comment by dweng0** [comment]
Can confirm it was a permissions issue and the workflow process will work in develop.

@Klazomenai When this is merged in to develop will reach out to you to run the necessary [command](https://quarto.org/docs/publishing/github-pages.html#github-action) to get the staging gh-page up and running
