### ISSUE TITLE
Some Anchor Links does not work correctly in chrome browser

### ISSUE THREAD

**Issue by jfaiza** [autonity/docs.autonity.org#160]
**For indication:** I detected this problem only on the **Chrome browser**.

**Description of the Problem:** 
For some pages of the documentation website the  "anchor links" don't work correctly.
Normally these links should takes the user directly to a particular section, but in these pages they only redirect it to the top of the page !

The pages concerned : from page https://docs.autonity.org/oracle/install-oracle/  to the end of the documentation.

**To Reproduce**
Exemple of anchor link : https://docs.autonity.org/oracle/install-oracle/#install-docker

**Comment by jay-cousins** [comment]
Hi @jfaiza - thank you for reporting this bug. A fix for this has been deployed.
