### ISSUE TITLE
Wrong link install docker at Set up node monitoring

### ISSUE THREAD

**Issue by Dedenwrg** [autonity/docs.autonity.org#163]
The link for installing Docker in the "Set up node monitoring" section of the documentation is pointing to the wrong location. Instead of directing users to the correct installation guide, it currently leads them to [this incorrect link](https://docs.autonity.org/node-operators/get-setup/#install-docker). The correct link for installing Docker should be [here](https://docs.autonity.org/node-operators/install-aut/#install-docker).

This issue impacts users attempting to set up node monitoring, as they may encounter confusion and difficulty finding the correct instructions for installing Docker.

**To Reproduce**

1. Navigate to the  [Set up node monitoring](https://docs.autonity.org/node-operators/setup-node-monitoring/#prerequisites). section of the documentation.
2. Look for the link labeled "install Docker".
3. Click on the link and observe that it redirects to the incorrect installation guide.

**Device information:**

- Device: xiaomi 
- OS: Android 12; M2012K11AG Build/SKQ1.211006.001
- Browser: Chrome 
- Browser Version: 120.0.6099.144

**Pull Request**

A pull request has been submitted to address this issue: [Pull Request #162](https://github.com/autonity/docs.autonity.org/pull/162).

**Comment by Dedenwrg** [comment]
Can I edit the label?

**Comment by Dedenwrg** [comment]
#162

**Comment by jay-cousins** [comment]
Thanks for reporting this valid bug @Dedenwrg . The associated PR has been merged in; it has been assessed as a Low bug for the Game. Thanks!
