### ISSUE TITLE
broken links in some documents

### ISSUE THREAD

**Issue by Dedenwrg** [autonity/docs.autonity.org#169]
There are some parts of the documentation that have broken links to the https://docs.autonity.org/account-holders//create-acct/ section.
#168

**Comment by jay-cousins** [comment]
Thanks for this and your PR fix @Dedenwrg , which has been merged in.

**Comment by jay-cousins** [comment]
Closing as completed, the fix PR has been merged in.  Thanks @Dedenwrg
