### ISSUE TITLE
Syntax Callout Blocks

### ISSUE THREAD

**Issue by Dedenwrg** [autonity/docs.autonity.org#171]
some sections in the documentation have syntax callout blocks that are not closed. This can cause confusion for the reader and needs to be corrected to ensure good readability and understanding.

**Comment by Dedenwrg** [comment]
#170

**Comment by jay-cousins** [comment]
Thanks for finding these formatting fixes @Dedenwrg and raising the PR to fix.  This is a valid bug report for the game, triaged as Low. Thanks for your contributions!
