### ISSUE TITLE
Typo in `Setting up custom networks` documentation

### ISSUE THREAD

**Issue by Klazomenai** [autonity/docs.autonity.org#175]
**Describe the bug**
There is a bug in the formatting of the `Setting up custom networks` for launching autonity. The `autonity` `command --http.vhosts \* \` is incorrectly formatted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.autonity.org/developer/custom-networks/
2. Scroll down to Step **4**
3. Run the `autonity` command with the flags specified
4. Try and connect to the `http.rpc` endpoint.

**Device information (please complete the following information):**
All connecting devices are affected. The issue resides with the `http.rpc` endpoint exposure.

**Comment by jay-cousins** [comment]
Docs updated in related PR #176 Thanks @Klazomenai 👍
