### ISSUE TITLE
Explain block proposer rewards are paid to validator account

### ISSUE THREAD

**Issue by aiman** [autonity/docs.autonity.org#178]
When a validator serves as committee member, they receive their share of staking rewards to their _treasury account_. However, they receive priority fees to their _validator account_.

I could only find four references to priority fee payment in the docs, across three pages:

> The priority fee ‘tip’ that may be specified in a transaction and which is given to the block proposer as an incentive for including the transaction in a block.
https://docs.autonity.org/concepts/validator/#validator-economics

> The optional priority fee of a transaction is not included in the rewards pool but awarded to the block proposer according to the EIP 1559 transaction fee mechanism.
https://docs.autonity.org/concepts/staking/#staking-rewards

> To incentivise inclusion of a transaction in a block, EIP 1559 allows a transaction to include an optional priority fee or ‘tip’ as a reward incentive to the block proposer for including the transaction in a block.
https://docs.autonity.org/concepts/system-model/#eip-1559-transaction-fee-mechanism-tfm

> the priority fee rewards are given to the block proposer per EIP 1559. In current state, the priority fee is paid to the proposing validator entity’s account every block.
https://docs.autonity.org/concepts/system-model/#autonity-eip-1559-configuration

The first three do not explain where the fees are sent to, and therefore it is a reasonable assumption is that the fees are paid to the _treasury account_, but this is not the case.

The last instance is poorly worded, because it makes use of the ambiguous expression "proposing validator entity's account", which is unnecessarily convoluted.

It is not immediately clear to the reader if this refers to the treasury account or the validator account. Why not just say so explicitly?

In any case, from the genesis reference, we can infer that this refers to the treasury account, which is incorrect:

> | `delegationRate` | The percentage fee of staking rewards that is deducted by validators as a commission from delegated stake. The fee is sent to the validator entity's account at epoch end on reward distribution....

**Comment by jay-cousins** [comment]
I agree. This needs an editorial to correct in a PR.

>The first three do not explain where the fees are sent to, and therefore it is a reasonable assumption is that the fees are paid to the treasury account, but this is not the case.

Agree.  These 3 pages are in the right place - it makes sense to refer to the tip reward in Validator and Staking Concepts under Validator economics and Staking rewards, and in the System model concept in the transaction fee mechanism where EIP-1559 is mentioned.

BUT, I think these 3 places should be (a) state the account it is sent to, (b) edited to simplify text where possible.

>The last instance is poorly worded, because it makes use of the ambiguous expression "proposing validator entity's account", which is unnecessarily convoluted.
>
>
It is not immediately clear to the reader if this refers to the treasury account or the validator account. Why not just say so explicitly?

Yes, agree.

>In any case, from the genesis reference, we can infer that this refers to the treasury account, which is incorrect:

| delegationRate | The percentage fee of staking rewards that is deducted by validators as a commission from delegated stake. The fee is sent to the validator entity's account at epoch end on reward distribution....

Yes, agree.

**Other edits?**

Also, in the Validator concept section [Validator identity, accounts, and keypairs](https://docs.autonity.org/concepts/validator/#validator-identity-accounts-and-keypairs), [Validator identifier](https://docs.autonity.org/concepts/validator/#validator-identifier) and [Treasury account](https://docs.autonity.org/concepts/validator/#treasury-account) - it should be clarified the _priority fee tip_ goes to the validator identifier and not the treasury account.

**Comment by jay-cousins** [comment]
Update: these changes will be made with edits for #186

**Comment by jay-cousins** [comment]
Edits made for this In PR #199 

To https://docs.autonity.org/concepts/validator/#validator-economics:

- Edited for this issue and issue #186 to rewrite the section. It now details incentives and disincentives. A table lists out the incentives with columns detailing the incentive, where paid, when paid, what it is: 

Economic gain | Receiving account | Distribution | Description
-- | -- | -- | --

Disincentives are clarified and linked off to https://docs.autonity.org/concepts/accountability/#slashing-economics (to avoid redundancy) where there is a parallel table for the penalties with headings so:

Economic loss | Receiving account | Distribution | Description
-- | -- | -- | --


To https://docs.autonity.org/concepts/staking/#staking-rewards:

- Edited https://docs.autonity.org/concepts/staking/#reward-distribution to clarify priority fee tip goes to validator identifier account

To https://docs.autonity.org/concepts/system-model/#eip-1559-transaction-fee-mechanism-tfm:

- no change as it is clarified in the following sub-section `/concepts/system-model/#autonity-eip-1559-configuration` - see beneath.

To https://docs.autonity.org/concepts/system-model/#autonity-eip-1559-configuration:

- the _priority fee_ rewards are given to the block proposer per EIP 1559. In current state, the priority fee is paid to the proposing validator node's [`validator identifier`](/concepts/validator/#validator-identifier) account every block.

Specific edits for this issue and #186  are in commits 5dd43bfcf08cc257ffe6c9a906e4ca45ccbf6cdf and a5b59e2d31928bbcb2681f119ef638dd711686a4.
