### ISSUE TITLE
Update to support Quarto 1.4+

### ISSUE THREAD

**Issue by aiman** [autonity/docs.autonity.org#181]
It is not possible to render the site with Quarto `1.4.551`, even in a fresh repo checkout. The error is one we have seen previously: `ERROR: Template partial ... was not found`.

**Comment by jay-cousins** [comment]
Yep, just upgraded locally and replicated the issue.

```bash
quarto --version
1.4.553
```

**Comment by dweng0** [comment]
have removed the unused partial and fix minor styling issue resulting in the quarto's bootstrap upgrade
