### ISSUE TITLE
No section in the documentation on the removal of awards from the validator's address

### ISSUE THREAD

**Issue by narko2t** [autonity/docs.autonity.org#185]
No section in documentation on removing awards from validator address to address tresure

Suppose the validator wants to send accumulated awards $ATN from the validator's address to the tresure address, but this section and command are not provided in the documentation

Accordingly, in order to somehow use these awards, for example, to sell them on CAX they must first be sent from the validator address, and then already take any further action, this should have been stated initially for everyone's understanding

command to be applied:
aut tx make --keyfile <path to validator key> --to <address tresure>  --value 20 | aut tx sign --keyfile <path to validator key> - | aut tx send -

this command can be added to the section: [Staking Recipes] (https://game.autonity.org/recipes/staking_recipes.html)

**Comment by jay-cousins** [comment]
Thanks for reporting this @narko2t 

Agree this can be clarified and improved.

I've created an issue #186 for clarifying the validator economics section to state which accounts receive validator income.

I've created an issue #187  to clarify specifying keyfile when chaining `aut` commands.

>this command can be added to the section: [Staking Recipes] (https://game.autonity.org/recipes/staking_recipes.html)

That is out of scope of this repo as it is game.autonity.org 
@rtedwardchen - what are your thoughts ? Another candidate to clarify this could be https://game.autonity.org/recipes/starter_recipes.html#submit-transactions

**Comment by rtedwardchen** [comment]
Currently, the Python recipes, including [starter recipes](https://game.autonity.org/recipes/starter_recipes.html) and [staking recipes](https://game.autonity.org/recipes/staking_recipes.html), are served as mini templates to help participants who are more familiar with Python start the games more easily. So, the Python recipes only demonstrate part of the functions in the [docs](https://docs.autonity.org/), and we expect participants to combine the Pyhon recipes with the [docs](https://docs.autonity.org/) to engineer their functions in Python. However, if the [docs](https://docs.autonity.org/) are improved, we can add more functions to the Python recipes to clarify specific use cases.

@cmjc I will have a further discussion with the team regarding this issue and potentially modify some of the Python recipes to help.

**Comment by narko2t** [comment]
Thanks for pointing this out!
