### ISSUE TITLE
Link to page "Bug Bounty" to update 

### ISSUE THREAD

**Issue by jfaiza** [autonity/docs.autonity.org#193]
I noticed that in the page [(https://docs.autonity.org/networks/testnet-piccadilly/)] the link to the page 'Bug Bounty" redirect the user to the page "https://game.autonity.org/#tasks--points".

> ![image](https://github.com/autonity/docs.autonity.org/assets/79405564/6ecca411-8084-4b63-bb78-3889ec7f88ec)

I think it will be better to redirect the user directly to the page "Bug Bounty" (Depending on round, For Round5: https://game.autonity.org/round-5/bug-bounty).

**Comment by jay-cousins** [comment]
Hi @jfaiza - you are correct, that is a broken link. Thank you for reporting this bug!
