### ISSUE TITLE
chainid for piccadily to update in "#setup-brownie"

### ISSUE THREAD

**Issue by jfaiza** [autonity/docs.autonity.org#194]
In the "Setup brownie" section in the page https://docs.autonity.org/developer/deploy-brownie/#setup-brownie , the example of the commande use wrong value for the piccadilly chainID:

> ![image](https://github.com/autonity/docs.autonity.org/assets/79405564/56ab5f7e-eecb-47fc-9103-333e8b856b2a)

**Comment by jay-cousins** [comment]
Hi thank you for spotting this @jfaiza - correct, this should be `65100002` (https://docs.autonity.org/networks/testnet-piccadilly/#piccadilly-testnet-details)

**Comment by jay-cousins** [comment]
To do with other chain ID updates tracked in issue #188
