### ISSUE TITLE
Update commands in Gas Guzzler doc

### ISSUE THREAD

**Issue by zigengZ** [autonity/docs.autonity.org#209]
**Describe the bug**

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to "https://game.autonity.org/getting-started/gas-guzzler.html"
2. In the section "Obtain gas statistics", find the commands mentioned for obtaining gas statistics.
Update the commands as follows:
Replace aut protocol get-minimum-base-fee with aut protocol minimum-base-fee.
Replace aut protocol get-block-period with aut protocol block-period.

![doc](https://github.com/user-attachments/assets/afeca3c3-7b3b-4227-8c03-ce88c0b3d2cb)
![lastest_aut_command](https://github.com/user-attachments/assets/e105567f-1522-4daf-ba02-ca05c42a0e82)

**Comment by aiman** [comment]
Thank you for reporting an issue with the content of the Piccadilly Circus Games Competition site <https://game.autonity.org>. This issue will be reviewed. However, it relates to a _different_ website than this one. This Github repo is not the appropriate place to report such issues, as a result it will be closed.
