### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by JackmooreCM** [autonity/docs.autonity.org#22]
This link does not work on the docs.autonity.org site

https://docs.autonity.org/howto/submit-trans/

**Comment by jay-cousins** [comment]
Hi @JackmooreCM Thank you for this. Can you clarify where you found this broken link?

Grepping the source content folder I am unable to find this legacy link from before the site's restructuring.

**Comment by aiman** [comment]
This may have been fixed in the meantime as I can't find a site that links to that URL any more. So issue can be closed.

**Comment by jay-cousins** [comment]
Closing. Please reopen is more is required.
