### ISSUE TITLE
Review repository development workflows

### ISSUE THREAD

**Issue by aiman** [autonity/docs.autonity.org#239]
The existing motivation for the `develop` branch is to have a place to document the changes for the upcoming version of Autonity itself, without publishing the changes live. After a major release, in theory the develop branch is unused, in recent past the branch was even deleted for periods of time.

So commits don't aways flow into `develop` first, and only then from `develop` to `master`. Rather, pull requests are often merged to `master` directly because the changes are required "now", and it is not desirable to wait for the rollout of the next Autonity version to ship.

This means we are de facto maintaining two separate sites at the same time, but development workflows may not be optimized for this. There should be a review of processes and systems to make sure they are fit for purpose.

**Comment by szemate** [comment]
In terms of workflows, I think we should distinguish between "content development" and "site development" (for design and tooling). I'd find it useful to create a separate development branch where we can merge and preview "site development" PRs without affecting the content.

**Comment by aiman** [comment]
> separate development branch where we can merge and preview "site development" PRs without affecting the content

If we had preview sites for every PR, would we still need such a permanent branch to preview "site development" changes?

**Comment by szemate** [comment]
> If we had preview sites for every PR, would we still need such a permanent branch to preview "site development" changes?

Only if we'd like to wait for multiple PRs to be merged before we publish the changes. But it can be managed with one-off branches too, so probably not.
