### ISSUE TITLE
Game RPC Node Submission form fails to accept DNS name in URL

### ISSUE THREAD

**Issue by h-faust** [autonity/docs.autonity.org#24]
https://game.autonity.org/rounds/round1/open_door/ links to a form for submitting a RPC node to the Game; however, it only accepted an IP address in the URL string ("http://51.75.146.144:8545") but not the DNS name of that same machine (" http://faustonode01.infocide.com:8545/")

**Comment by dtebbs** [comment]
Closing.  This does not seem to be a documentation issue.  Please re-open if I've missed something.

**Comment by h-faust** [comment]
As a member of the public, I can't re-open, but more importantly: where _should_ a bug like this be reported? 

I just tried it, and the problem still persists on https://game.autonity.org/incentive-game-forms-frontend/rpc.html

In _addition_ I found that a trailing slash when giving an IP address (i.e. "http://51.75.146.144:8545/") _also_ seems to be an issue for the form, but "http://51.75.146.144:8545" works. I would also consider this a bug, since a URL with a slash at the end is perfectly valid.

**Comment by flofrie** [comment]
Re-opening, since this is a good and relevant example of how we handle a submission from an external user. This is a real bug in the forms, and the Doc repo is the only one where a user can submit a bug. (Other than the autonity code repo itself, which seems even less suitable). 

So, what do we do?

**Comment by jay-cousins** [comment]
Closing. This does not seem to be a documentation issue.
