### ISSUE TITLE
Bug Submission: UI issue in heading 

### ISSUE THREAD

**Issue by raj-shekhar1** [autonity/docs.autonity.org#25]
**Describe the bug**
Issue with page heading in the below page - 
https://docs.autonity.org/developer/deploy-brownie/

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'https://docs.autonity.org/developer/deploy-brownie/'
2. See UI issue in the heading.

![Screenshot from 2023-01-31 11-48-01](https://user-images.githubusercontent.com/55439064/215752127-ad4f7fd3-1a60-476b-afe0-5d10e41bb6a4.png)

**Device information (please complete the following information):**
Not Needed

**Comment by jay-cousins** [comment]
Thanks @raj-shekhar1 - this has been fixed in https://github.com/autonity/docs.autonity.org/pull/23.

Closing for now. Please reopen if you think something is missing.
