### ISSUE TITLE
Discussion on enabling GitHub links 

### ISSUE THREAD

**Issue by dweng0** [autonity/docs.autonity.org#255]
### Description

Quarto provides an option to allow pages to have GitHub links that link directly to "edit", "view source" and "raise issue". Is this something that we would want to leverage

### Rationale

Enabling this functionality may help to "crowdsource" any issues, allowing users to raise issues/suggest edits with a few clicks.

### Implementation

The option can be enabled in the quarto yaml file. Details are available [here](https://quarto.org/docs/websites/website-navigation.html#github-links)

![Image](https://github.com/user-attachments/assets/e29eb51a-5036-461a-a6cf-a084b9800e01)

**Comment by aiman** [comment]
Yes this feature should be enabled
