### ISSUE TITLE
Incorrect paths in Cloudflare Preview workflow

### ISSUE THREAD

**Issue by aiman** [autonity/docs.autonity.org#262]
In `.github/workflows/cloudflare-preview.yml` on `master`:

>      - name: Render and Publish
>        uses: quarto-dev/quarto-actions/render@v2
>        with:
>          to: html
>
>      - name: Publish to Cloudflare Pages
>        id: cloudflare_deploy
>        uses: cloudflare/pages-action@v1
>        with:
>          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
>          accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
>          projectName: docs-autonity-org
>          directory: ./docs
>          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

Why is `to: html` in render but then it is `./docs` in publish?

@szemate @dweng0

**Comment by dweng0** [comment]
@aiman this is telling the quarto compiler to render output as html <https://github.com/quarto-dev/quarto-actions/tree/v2/render#usage>

**Comment by aiman** [comment]
OK got it, false alarm!
