### ISSUE TITLE
General documentation feedback

### ISSUE THREAD

**Issue by spenot09** [autonity/docs.autonity.org#37]
# Feedback on running a node
Overall the documentation and explanation of setting up a validator node was brilliant and easy to follow.
Below I have included some of my suggestions and feedback on various aspects of the documentation that I think may further improve the user experience. Thank you!

## [Installing the Docker image](https://docs.autonity.org/node-operators/install-aut/#install-docker) 
1. The docker image location in [Step 4.](https://docs.autonity.org/node-operators/install-aut/#install-docker:~:text=docker%20pull%20ghcr,Copy) appears to show the location to be `ghcr.io/autonity/autonity/autonity:latest` whereas the actual location is `ghcr.io/autonity/autonity:latest`
	
## [Run Autonity](https://docs.autonity.org/node-operators/run-aut/#run-docker)
1. Would be nice to include example logs that are expected when in healthy state. This would provide reassurance that the steps are indeed being followed correctly.
2. Before beginning the sync with the blockchain, a notice recommending a stable internet connection may be beneficial as peer connections may drop otherwise.

## [Connecting to node](https://docs.autonity.org/account-holders/setup-autcli/#configure)
1. Appears that the [example RPC URL](https://docs.autonity.org/account-holders/setup-autcli/#configure:~:text=rpc_endpoint%3Dhttps%3A//NETWORK_NAME.autonity.org) is missing the `rpc1.` prefix in `https://NETWORK_NAME.autonity.org
`. When navigating to the [example page](https://docs.autonity.org/networks/testnet-piccadilly/#:~:text=https%3A//rpc1.piccadilly.autonity.org/) of Piccadilly the expected format  is `https://rpc1.piccadilly.autonity.org/`

## [Registering a Validator](https://docs.autonity.org/validators/register-vali/#step-1-generate-a-cryptographic-proof-of-node-ownership)
1. Perhaps guiding readers that when running Docker they have to shell into the running container and run the`autonity genEnodeProof --nodekey <NODE_KEY_PATH> <TREASURY_ACCOUNT_ADDRESS>` command from there. May not be obvious to all users.

## [Determining Enode address](https://docs.autonity.org/validators/register-vali/#step-2-determine-the-validator-enode-and-address)
1. The aut cli does not expose the the `aut validator compute-address` subcommand and returns the following error `Error: No such command 'compute-address'` (Edit: I was running an older version of `aut` which was resolved upon update)

## [Hardware Requirements](https://docs.autonity.org/node-operators/install-aut/#hardware)
1. The minimum hardware requirements are perhaps overstated (especially for a testnet). Also, once the games begin on Piccadilly, the storage requirements will not be so great as the network will be restarted frequently.
2. Would be fantastic if there was a feature where current and projected data storage requirments could be observed, in order to allow validator operators to make better hardware decisions. 
3. If there was a "live sync" time that could be seen (i.e. how long it would take a new node to sync the current chain depending on sync mode) that would be immensely useful as I often find myself guessing this (quite inaccurately) with other clients.

**Comment by flofrie** [comment]
> ## [Determining Enode address](https://docs.autonity.org/validators/register-vali/#step-2-determine-the-validator-enode-and-address)
> 
> 1. The aut cli does not expose the the `aut validator compute-address` subcommand and returns the following error `Error: No such command 'compute-address'`

According to https://github.com/autonity/autcli/issues/95 it seems you may just not have tried the latest version of `aut`.

**Comment by spenot09** [comment]
@flofrie ah that is indeed the case! Thank you.

**Comment by flofrie** [comment]
> [Registering a Validator](https://docs.autonity.org/validators/register-vali/#step-1-generate-a-cryptographic-proof-of-node-ownership)
>
>    Perhaps guiding readers that when running Docker they have to shell into the running container and run the autonity genEnodeProof --nodekey <NODE_KEY_PATH> <TREASURY_ACCOUNT_ADDRESS> command from there. May not be obvious to all users.

As I understand it, when running Docker as suggested in https://docs.autonity.org/node-operators/run-aut/, where `--volume` maps the `autonity-chaindata` directory to a directory _outside_ your running container, you don't actually need to execute the `genEnodeProof` within your running container. You can start a _different_ container mapping to the same chaindata directory.

I did it with `docker run -t -i --volume $(pwd)/autonity-chaindata:/autonity-chaindata --name autonity-proof --rm ghcr.io/autonity/autonity:latest genEnodeProof --nodekey ./autonity-chaindata/autonity/nodekey <ACCOUNT_ADDRESS>`

**Comment by flofrie** [comment]
> ## [Installing the Docker image](https://docs.autonity.org/node-operators/install-aut/#install-docker)
> 
>1. The docker image location in [Step 4.](https://docs.autonity.org/node-operators/install-aut/#install-docker:~:text=docker%20pull%20ghcr,Copy) appears to show the location to be `ghcr.io/autonity/autonity/autonity:latest` whereas the actual location is `ghcr.io/autonity/autonity:latest`

Also reported in https://github.com/autonity/docs.autonity.org/issues/19 and now fixed in https://github.com/autonity/docs.autonity.org/pull/39

**Comment by flofrie** [comment]
> ## [Connecting to node](https://docs.autonity.org/account-holders/setup-autcli/#configure)
> 
> 1. Appears that the [example RPC URL](https://docs.autonity.org/account-holders/setup-autcli/#configure:~:text=rpc_endpoint%3Dhttps%3A//NETWORK_NAME.autonity.org) is missing the `rpc1.` prefix in `https://NETWORK_NAME.autonity.org `. When navigating to the [example page](https://docs.autonity.org/networks/testnet-piccadilly/#:~:text=https%3A//rpc1.piccadilly.autonity.org/) of Piccadilly the expected format  is `https://rpc1.piccadilly.autonity.org/`

Fixed in https://github.com/autonity/docs.autonity.org/pull/40

**Comment by jay-cousins** [comment]
Thank you for your feedback @spenot09 and the PR's @flofrie .

Status update: #39 and #40 are approved and merged in.  Still some open discussion on #38 .

**Comment by spenot09** [comment]
No worries @cmjc! Thanks for taking the feedback onboard. 

Re #38 there's definitely a number of ways it could be tackled.

**Comment by jay-cousins** [comment]
>Re https://github.com/autonity/docs.autonity.org/pull/38 there's definitely a number of ways it could be tackled.

Agree @spenot09 ! That's merged in after consensus review. Reviewing this issue, I think the only outstanding item is the Hardware RQs question.

>1. The minimum hardware requirements are perhaps overstated (especially for a testnet). Also, once the games begin on Piccadilly, the storage requirements will not be so great as the network will be restarted frequently.

This is the current recommendation from the core development team. Will pass this feedback to them.

>2. Would be fantastic if there was a feature where current and projected data storage requirements could be observed, in order to allow validator operators to make better hardware decisions.

Can you elaborate more on this, please?

I'm understanding this atm as something like:

- Goal to understand current and future storage requirements
- By an ability to:

    - show current data storage requirements for a node? E.g. to answer the question "At current block height how much storage space do I need for the local data store on my node?"
    - project future data storage requirements for a node?  E.g. to answer the question "At a future block height XYZ, how much storage space do I need for the local data store on my node?" Or, "What is the projected rate of growth in system state over time based on growth to date?"

>3. If there was a "live sync" time that could be seen (i.e. how long it would take a new node to sync the current chain depending on sync mode) that would be immensely useful as I often find myself guessing this (quite inaccurately) with other clients.

Got it. Question here is simply "How long left to sync"?

**Comment by spenot09** [comment]
Hi @cmjc, definitely! With regards to the data storage requirements projection, you are spot on.

If a validator wishes to run a node in a cloud based environment they will have a large selection of VMs to choose from (and thus cost optimise for). If current live data storage requirements could be transaprently seen then they can make a swift choice as to best setup. A similar story would also hold true for non-cloud based solutions.

With regards to having future projections, I would perhaps envisage this as a "worst-case/best-case" curve which would then allow validators to plan out a hardware upgrade strategy as the chain progresses over time.

In terms of the "live sync" feature, I meant more as in "If I were to sync the entire chain right now, how long would it take from scratch?". Whilst of course this would also be hardware dependent (amongst other things) perhaps a short form filling out RAM/CPU etc. could be used to provide a rough estimate. Such a feature would be terrific especially in high pressure situations when a validator goes down and a fix has to be put in place ASAP. Having this information to hand would allow validator teams to make better informed decisions and reduce the guesswork. 

Thanks for taking my feedback on board and please do let me know if anything is unclear!

**Comment by jay-cousins** [comment]
Hi @spenot09 - an update on your comments under the [Hardware Requirements](https://docs.autonity.org/node-operators/install-aut/#hardware) heading above:

>1. The minimum hardware requirements are perhaps overstated (especially for a testnet). Also, once the games begin on Piccadilly, the storage requirements will not be so great as the network will be restarted frequently.

This has been reviewed by the development team and the HW requirements updated. This has updated the **Recommended** RQs; the **At least** RQs remain the same.

>2. Would be fantastic if there was a feature where current and projected data storage requirements could be observed, in order to allow validator operators to make better hardware decisions.
>3. If there was a "live sync" time that could be seen (i.e. how long it would take a new node to sync the current chain depending on sync mode) that would be immensely useful as I often find myself guessing this (quite inaccurately) with other clients.

3. has also been raised on the Autonity Discord. There is now an issue covering 2,3 on the Autonity Go client repo.  See: https://github.com/autonity/autonity/issues/793.

**Comment by jay-cousins** [comment]
I think the open comments have now been addressed and this issue can be closed.

**Comment by jay-cousins** [comment]
Closing as done @spenot09
