### ISSUE TITLE
16 cores or threads?

### ISSUE THREAD

**Issue by flofrie** [autonity/docs.autonity.org#43]
Recommended HW requirements on https://docs.autonity.org/node-operators/install-aut/ say:

* 3.10 GHz with 16 CPU’s

Does that mean 16 cores, or 16 threads? (I would think 8C/16T is plenty; and minimum of 4C/8T works pretty well.)

Also, 8GB _recommended_, not 16GB? (I thought 8GB is really the minimum; and 16GB desirable if there's load?)

**Comment by Jason-Zhangxin-Chen** [comment]
@flofrie 
> Recommended HW requirements on https://docs.autonity.org/node-operators/install-aut/ say:
> 
> * 3.10 GHz with 16 CPU’s
> 
> Does that mean 16 cores, or 16 threads? (I would think 8C/16T is plenty; and minimum of 4C/8T works pretty well.)
> 
In case of computing specification, it refers to 16 cores with each of them have 3.1GHz. 
> Also, 8GB _recommended_, not 16GB? (I thought 8GB is really the minimum; and 16GB desirable if there's load?)

8GB is minimum, 16GB should be preferred.

Note, remember that the HW specification here also takes omission fault detection protocol into account, which means we reserved some space for the future protocol development, for example, in omission fault detection protocol, we would introduce BLS pairing algorithms for massive consensus message aggregation for the omission fault accountability.
