### ISSUE TITLE
ADD How to: Deploy smart contracts to an Autonity network with Brownie

### ISSUE THREAD

**Issue by jay-cousins** [autonity/docs.autonity.org#5]
### Description

We have how to's for deploying a contract to Autonity testnet using Node and Truffle.

The aut CLI tool is written in Python, so it makes sense to have a how to using the Python Brownie framework.

The how to should deploy to an Autonity Testnet.

### Tasks

- [x] Create How to deploying contract using Brownie framework.

### Implementation

Use Python Brownie framework, ref: https://eth-brownie.readthedocs.io/en/stable/deploy.html

**Comment by dtebbs** [comment]
The brownie docs do a pretty good job of describing this: https://eth-brownie.readthedocs.io/en/stable/deploy.html
We might consider just demonstrating how to add an Autonity local `--dev` network and a live testnet.  
https://eth-brownie.readthedocs.io/en/stable/network-management.html#network-management

**Comment by dtebbs** [comment]
Closing as done.  Please reopen if necessary.
