### ISSUE TITLE
Typo on 'Create an account' page

### ISSUE THREAD

**Issue by Ben-Haslam** [autonity/docs.autonity.org#51]
A code block on [this](https://docs.autonity.org/account-holders/create-acct/#create-account-using-aut) page has a typo `key-file` so does not work. 

```
mkdir keystore
aut account new --key-file ./keystore/alice.key
```

Corrected:

```
mkdir keystore
aut account new --keyfile ./keystore/alice.key
```

**Comment by jay-cousins** [comment]
Thanks for finding this @Ben-Haslam ! This is legacy syntax from an earlier version of `aut`. It should be `--keyfile` as you report.

PR to correct this here #52
