### ISSUE TITLE
Restructuring

### ISSUE THREAD

**Issue by dtebbs** [autonity/docs.autonity.org#6]
### Description

We've discussed re-organising into a setion per "role" or "participant type", which I think we agree on.
We might also consider further re-ordering, so that the "guide" content comes first, and the deeper architecture stuff comes later.

My reasoning is that many of these pages actually go quite deep into the mechanisms (which is actually great - I find it very frustrating when a new chain doesn't make these details readily available), but a large fraction of the audience are going to want to know the high-level roles (Account holder, delegator, node operator, validator), determine which one they want to take on, and dive right in.

There is some high-level info that needs to be made clear up front, but I think this is basically the current "Autonity" top-level page.

So I'm suggesting a restructure that's something like:
```
     - [ ] [10] "Overview" (current content of the Autonity section page -
       mention the high-level tech points, and focus on the
       participant roles: Account Holder, Delegator, Operator, Validator.  See "architecture" (below) for details.)
     - [ ] [20] "Account Holder"
       - Setup AUT cli
       - Create an account
       - Fund an account (combine with the above page?)
       - Submit a transaction (and make queries)
     - [ ] [30] "Delegator"
       - Bond
       - Unbond
       - Claim rewards
       - Transfer LNTN
     - [ ] [40] "Operator"
       - Install Autonity
       - Run Autonity
       - Setup Node Monitoring
     - [ ] [50] "Validator"
       - Register
       - Pause
       - Reactivate
       - Change commission rate
     - [ ] [60] "Developer"  (Hidden, whatever is left howtos)
     - [ ] [70] "Networks"
     - [ ] [80] "Concepts" (use content from current "Architecture")
       - ... all the pages currently under "Autonity"
     - [ ] [90] "Reference"
       - as-is
     - [ ] [100] "Glossary"
       - as-is
     - [ ] [110] "Known Issues"
       - as-is
```

### Implementation

- [x] update the front page to link to top-level sections
- [x] "key concepts" from "Node Operators" into "Overvew"
  - [x] Newton
  - [x] (Liquid) Staking - cover Liquid Newton
  - [x] paticipant node
  - [x] validator node
  - [x] consensus committee
- [x] link to networks from overview

**Comment by jay-cousins** [comment]
Done in PR #4 

Closing.
