### ISSUE TITLE
Correcting the Sequence of Executions in "How to enroll in Onboard Validator" Guide

### ISSUE THREAD

**Issue by ravinayag** [autonity/docs.autonity.org#62]
### Description

> **Explain the new feature or suggested improvement in as much detail as you can.**

As a beginner, I found that the sequence of executions for step 3 in the "How to enroll in Onboard Validator" guide is misleading:
https://game.autonity.org/round-2/on-chain-tasks/onboard-validator/

Currently, the sequence is:
- aut account sign-message --help
- aut account import-private-key --help

Following this sequence will lead to errors, as the "sign-message" command expects a private_key file with a string. 
As users should first generate the private_key file using "import-private-key" and then use "sign-message".

> **Who are the expected users of the improvement?**

All beginners who are new to the project.

> **What is the impact of the improvement on the documentation website and its users?**

By providing a clearer and more accurate sequence of command executions, users will be able to follow the guide more effectively, reducing potential confusion and errors.

### Rationale

> **Why should this improvement be made? Why is it worthwhile to develop and implement?**

The current sequence is misleading, causing users to encounter errors and potentially require additional assistance. Adjusting the sequence to follow the correct workflow will improve the user experience and reduce the likelihood of errors.

### Implementation

> **Do you have ideas regarding the implementation of this feature?**

Simply interchanging the sequence of the two commands mentioned in step 3 will enhance the user experience and reduce the likelihood of errors.

>  **Are you willing to implement this feature?**

Yes

**Comment by jay-cousins** [comment]
Hi @ravinayag Thank you for this feedback. A PR has been raised for this edit and the website will update soon.

The `game.autonity.org` website isn't part of `docs.autonity.org` and isn't one of the [4 eligible project repos for the Bug Bounty](https://game.autonity.org/round-2/bug-bounty/#synopsis). So this isn't a valid submission to the Bug Bounty and doesn't count towards Games points.

Closing this issue. Please re-open if you think something isn't covered.

**Comment by ravinayag** [comment]
@cmjc , My understanding to the info supplied that  the  `docs.autonity.org`   is part of the bug bounty program as per the link for your ref. 
https://game.autonity.org/round-2/bug-bounty/#synopsis
![image](https://user-images.githubusercontent.com/52193049/235827450-f3b0f259-0125-4bbc-ad3c-17b856948435.png)

**Comment by jay-cousins** [comment]
Hi @ravinayag. The Bug Bounty is against the above 4 eligible projects. `docs.autonity.org` is the repo for the content of  https://docs.autonity.org/ which is the documentation site for the Autonity Go Client.

The https://game.autonity.org/ website is not part of the https://docs.autonity.org/ website or repo. 

So submitting a bug report for the game.autonity.org website is not eligible for the Bug Bounty.
