### ISSUE TITLE
The maximum amount sent by the faucet is 10ATN

### ISSUE THREAD

**Issue by jfaiza** [autonity/docs.autonity.org#67]
**Describe the bug**

When I use the Faucet "https://faucet.autonity.org/" indicated in the documentation of Autonity, and I try to send more than 10 ATN the faucet only sends me 10 ATN!!

Either it's a bug in the faucet or it's a limitation that you fixed.  But if it's a limit, I think it should be indicated in the websitesite or in the documentation, or display an error message when trying to sending an amount greater than 10 ATN.

**Comment by dweng0** [comment]
Hi @jfaiza , There should be an error message if you try to send more then 10 ATN, will take a look

**Comment by jfaiza** [comment]
Hi @dweng0 ,
I try to send 100ATN in the example below. There is no error message displayed : 
![image](https://github.com/autonity/docs.autonity.org/assets/79405564/298e53e2-a1c4-466b-a33c-5e8bf72fe5bb)

**Comment by dweng0** [comment]
> Hi @dweng0 , I try to send 100ATN in the example below. There is no error message displayed...

There is a limit of 10 ATN on the server (this is intentional), the UI isn't reflecting this fact, will look to update this in due course

**Comment by dweng0** [comment]
@jfaiza , This has been updated and the UI should provide more contextual feedback for users. Please note that the Faucet is not part of the [Bug Bounty](https://game.autonity.org/round-3/bug-bounty/#synopsis) list in the games, so no points can be awarded for this issue

**Comment by jfaiza** [comment]
> @jfaiza , This has been updated and the UI should provide more contextual feedback for users. Please note that the Faucet is not part of the [Bug Bounty](https://game.autonity.org/round-3/bug-bounty/#synopsis) list in the games, so no points can be awarded for this issue

OK.
