### ISSUE TITLE
The delay of "Change validator commission rate Delay" of "Autonity Utility Tool (aut)" is not noted in the documentation 

### ISSUE THREAD

**Issue by jfaiza** [autonity/docs.autonity.org#68]
I try to change the commission rate of my validator using the aut function `aut validator change-commission-rate --validator` , but the the change was only processed after several hours.

**Problem:** In the documentaion you don't note this delay!
**Proposal** : I Think this delay should be noted as it is made for the function `aut validator bond --validator`, it is noted "_Bonding requests are not processed until the end of the current epoch. ..._"

**Comment by jay-cousins** [comment]
Thank you for reporting this @jfaiza . Commission rate changes are subject to the same unbonding period constraint as staking transitions. On commit of the rate change transaction, the unbonding period begins and the rate change is applied at the end of the epoch in which the unbonding period expires.

(See code: https://github.com/autonity/autonity/blob/e1e8e257c45f28b2553edbeca32c6e9f60523d83/autonity/solidity/contracts/Autonity.sol#L431 )

This is *not* clear in the docs and is a valid bug report.

On your **Proposal**:

>Proposal : I Think this delay should be noted as it is made for the function aut validator bond --validator, it is noted "Bonding requests are not processed until the end of the current epoch. ..."

Agree. A similar note to that in https://docs.autonity.org/delegators/bond-stake/#bond-newton-to-validator should be added to https://docs.autonity.org/validators/change-commission-rate/#change-validator-commission-rate (after Step 1.)

Also,  the following edits lgtm:

- https://docs.autonity.org/reference/api/aut/op-prot/#finalize  - add bullet point "applies any validator commission rate changes - pending rate change requests tracked in CommissionRateChangeRequest data structures in memory"
- https://docs.autonity.org/concepts/validator/#validator-economics - edit sentence "After registration the validator can modify its commission rate (see [changeCommissionRate](https://docs.autonity.org/reference/api/aut/#changecommissionrate) )." to clarify rate change is applied at epoch end.

**Comment by jay-cousins** [comment]
@jfaiza - A PR to close this issue has been created here - https://github.com/autonity/docs.autonity.org/pull/69
