### ISSUE TITLE
Remove title from nav bar

### ISSUE THREAD

**Issue by dweng0** [autonity/docs.autonity.org#76]
### Description

I believe the title "**docs.autonity.org**" is unnecessary given it will already be in the url bar, and "documentation" is headlined below. 
![image](https://github.com/autonity/docs.autonity.org/assets/5268627/74212686-c6de-4e62-8b16-5730f15a5efb)

I propose its removal in order to streamline the look and feel of the documentation site
...

### Rationale

I believe this will helps to declutter the documentation such that only relevant information is displayed. If users wish to return to the home page, they can click on the logo, which has the same functionality as the title (a clickable link to the home page).

The end result would look something like this:
![image](https://github.com/autonity/docs.autonity.org/assets/5268627/e7e7579d-5942-4520-9d9a-a232a48872c7)

### Implementation
Update the `navigation.html` partial (or add one if not already in place) and remove the title shortcode. I recommend this approach because modifying the title so it is an empty string will result in an empty clickable area.

**Comment by aiman** [comment]
This is actually confusing, because when people click on the Autonity logo, they may expect to go the autonity.org page. So I think we still need to retain something in the nav bar, it just doesn't have to be the URL. So would propose "docs" next to the Autonity logo. And I think the term `Documentation` itself, in the TOC sidebar, is what should be removed.

**Comment by jay-cousins** [comment]
The term `Documentation` can be easily changed or just removed. It is set as the linkTitle in the page metadata of the root `_index.md`:

```yaml
---
# title: "Welcome to Autonity!"
linkTitle: "Documentation"
type: docs
...
```

Leaving `linkTitle` empty will just remove it.

**Comment by jay-cousins** [comment]
Closing as PR merged.
