### ISSUE TITLE
Update docs for change of `snap` to `aut-snap`

### ISSUE THREAD

**Issue by jay-cousins** [autonity/docs.autonity.org#78]
**Description**

The snap protocol is being renamed from `snap` to `aut-snap` by https://github.com/autonity/autonity/pull/805. This addresses issue https://github.com/autonity/autonity/issues/791, which is logged in the docs.autonity.org site as a Known issue at: https://docs.autonity.org/issues/#error-snapshot-extension-registration-failed.

Note that the `--syncmode` flag option `snap` is not renamed and no other change is needed in the docs for this.

**Tasks**

- [x] remove known issue https://docs.autonity.org/issues/#error-snapshot-extension-registration-failed

**Comment by yazzaoui** [comment]
The cli option for the snap syncmode `--syncmode "snap"` remains unchanged.
